/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#745c00',
        'outline': '#76777d',
        'on-tertiary-fixed-variant': '#444749',
        'primary-fixed': '#dae2fd',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary-fixed-variant': '#574500',
        'error': '#ba1a1a',
        'tertiary': '#000000',
        'secondary-fixed-dim': '#e9c349',
        'tertiary-container': '#191c1e',
        'on-tertiary-fixed': '#191c1e',
        'background': '#f8f9ff',
        'on-tertiary-container': '#818486',
        'surface-container-high': '#dce9ff',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#c6c6cd',
        'surface-container-highest': '#d3e4fe',
        'surface': '#f8f9ff',
        'surface-variant': '#d3e4fe',
        'primary': '#000000',
        'on-surface': '#0b1c30',
        'primary-container': '#131b2e',
        'inverse-on-surface': '#eaf1ff',
        'on-error-container': '#93000a',
        'surface-dim': '#cbdbf5',
        'surface-container': '#e5eeff',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed': '#ffe088',
        'on-surface-variant': '#45464d',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#bec6e0',
        'tertiary-fixed-dim': '#c4c7c9',
        'on-primary-container': '#7c839b',
        'inverse-surface': '#213145',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#bec6e0',
        'surface-tint': '#565e74',
        'surface-bright': '#f8f9ff',
        'on-secondary-fixed': '#241a00',
        'on-background': '#0b1c30',
        'on-primary': '#ffffff',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#e0e3e5',
        'secondary-container': '#fed65b',
        'surface-container-low': '#f5f5f5',
        'on-secondary': '#ffffff',
        'secondary': '#735c00',
        // Keep primary-600 alias for backward compat
        'primary-600': '#131b2e',
        'primary-700': '#0f1520',
        'primary-100': '#dce9ff',
        'primary-50': '#eff4ff',
        // Semantic aliases for dark-surface text
        'navy': '#131b2e',
        'gold': '#e9c349',
        'gold-dark': '#735c00',
        'navy-text': '#ffffff',
        'navy-text-muted': 'rgba(255,255,255,0.7)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'label-caps': ['DM Sans', 'sans-serif'],
        'headline-xl': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      spacing: {
        'unit': '8px',
        'margin-desktop': '64px',
        'gutter': '24px',
        'section-gap': '120px',
        'margin-mobile': '20px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      boxShadow: {
        'ambient': '0 8px 30px rgb(11,28,48,0.04)',
        'ambient-hover': '0 20px 40px rgb(11,28,48,0.08)',
        'card': '0 8px 30px rgba(11,28,48,0.06)',
      },
    },
  },
  plugins: [],
}
